language: node_js # node环境
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run docs:build # 执行命令
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist # 部署的文件夹文件
  github-token: $GITHUB_TOKEN # travis服务上的token变量
  target-branch: gh-pages # 集成发布到gh-pages上
  keep-history: true
  on:
    branch: main
notifications:
  email: true